import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,html}'],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f5',
        'surface-dim': '#dcdad6',
        'surface-bright': '#fcf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ef',
        'surface-container': '#f0ede9',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e5e2de',
        'on-surface': '#1c1c1a',
        'on-surface-variant': '#4b454b',
        'inverse-surface': '#31302e',
        'inverse-on-surface': '#f3f0ec',
        outline: '#7c757b',
        'outline-variant': '#cdc4cb',
        'surface-tint': '#5f6229',
        primary: '#1e2000',
        'on-primary': '#ffffff',
        'primary-container': '#333602',
        'on-primary-container': '#9da060',
        'inverse-primary': '#c8cb87',
        secondary: '#71594d',
        'on-secondary': '#ffffff',
        'secondary-container': '#fddccc',
        'on-secondary-container': '#785f53',
        tertiary: '#1d1e1d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#323331',
        'on-tertiary-container': '#9b9b99',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e4e7a1',
        'primary-fixed-dim': '#c8cb87',
        'on-primary-fixed': '#1b1d00',
        'on-primary-fixed-variant': '#474a14',
        'secondary-fixed': '#fddccc',
        'secondary-fixed-dim': '#dfc0b1',
        'on-secondary-fixed': '#28180e',
        'on-secondary-fixed-variant': '#584237',
        'tertiary-fixed': '#e3e2e0',
        'tertiary-fixed-dim': '#c7c6c4',
        'on-tertiary-fixed': '#1a1c1a',
        'on-tertiary-fixed-variant': '#464745',
        background: '#fcf9f5',
        'on-background': '#1c1c1a',
        'surface-variant': '#e5e2de',
      },
      spacing: {
        'stack-sm': '12px',
        'stack-md': '24px',
        'margin-mobile': '20px',
        gutter: '24px',
        unit: '8px',
        'margin-desktop': '64px',
        'container-max': '1280px',
        'stack-lg': '48px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-sm': ['Noto Serif', 'serif'],
        'headline-md': ['Noto Serif', 'serif'],
        'display-lg': ['Noto Serif', 'serif'],
        'display-lg-mobile': ['Noto Serif', 'serif'],
        'label-md': ['Space Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        caption: ['Space Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        'body-md': ['Space Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        'body-lg': ['Space Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
      },
      fontSize: {
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        caption: ['10px', { lineHeight: '14px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config;
